version: "3.8"

services:
  backend:
    container_name: app-cont
    build: .
    ports:
      - "8080:8080"
    image: underpocker/travelmap-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travelmap
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=springcourse
    depends_on:
      - mysql

  mysql:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    image: underpocker/travelmap-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=springcourse
      - MYSQL_DATABASE=travelmap
