version: "3.8"

services:
  backend:
    container_name: app-cont
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travelmap
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=springcourse
    depends_on:
      - mysql

  mysql:
    container_name: db
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=springcourse
      - MYSQL_DATABASE=travelmap
